bybitPositionAccount:
        futuresAccountSizeUsd: 63
        riskPerTradeUsd: 21
        usedMarginAccount: 0.45
        bybitApi:
                testnet: True
                apiKey: 
                secretKey:
        triggerPriceDistancePercentage: 0.02
        auditLogPath: "/home/jirka/log/trading-backoffice/bybit-position-portfolio-audit-log.csv"

bybitSwingAccount:
        futuresAccountSizeUsd: 42
        riskPerTradeUsd: 21
        usedMarginAccount: 0.45
        bybitApi:
                testnet: True
                apiKey: 
                secretKey:
        triggerPriceDistancePercentage: 0.02
        auditLogPath: "/home/jirka/log/trading-backoffice/bybit-swing-portfolio-audit-log.csv"

bybitIntradayAccount:
        futuresAccountSizeUsd: 10
        riskPerTradeUsd: 0.5
        usedMarginAccount: 0.45
        bybitApi:
                testnet: True
                apiKey: 
                secretKey: 
        triggerPriceDistancePercentage: 0.02
        auditLogPath: "/home/jirka/log/trading-backoffice/bybit-intraday-portfolio-audit-log.csv"
